
#define BUTTON_ON_TIME 200


// DISPLAY

#ifdef TML_DISPLAY == LCD_TFT_320x240 
    #define _TML_RESOLUTION_WIDTH 320
    #define _TML_RESOLUTION_HEIGTH 240
#elif TML_DISPLAY == LCD_TFT_320x480
    #define _TML_RESOLUTION_WIDTH 320
    #define _TML_RESOLUTION_HEIGTH 480
#endif