name: Arduino Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Install Libraries
        run: |
          pio lib install "TFT_eSPI"
          pio lib install "SPI"
          pio lib install "FS"
          pio lib install "SPIFFS"
          
      - name: Run PlatformIO tests
        run: pio test
