name: Arduino Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup PlatformIO
      uses: platformio/platformio-action@v1
      with:
        install-deps: true
        test-flags: -e esp8266 
    - name: Test
      run: pio test
